name: Docker Build Test

# 언제 일할까? -> main 브랜치에 코드가 push 되었을 때
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # 우분투(리눅스) 환경에서 실행해라
    runs-on: ubuntu-latest

    steps:
    # 1. 우리 코드를 내려받아라
    - uses: actions/checkout@v3

    # 2. 도커 이미지를 빌드해봐라 (잘 만들어지는지 테스트)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-custom-nginx:$(date +%s)
